[aliases]
l = ["log", "--reversed"]
s = ["l", "-r", "stack()"]
wip = ["l", "-r", "wip()"]
heads = ["l", "-r", "wip_heads()"]

[revset-aliases]
"stack()" = "fork_point(mutable()::@)- | fork_point(mutable()::@)::"
"wip()" = "mutable()- | mutable()::heads(mutable())"
"wip_heads()" = "heads(mutable() & mine() & empty())- | heads(mutable() & mine() & ~empty())"

[git]
subprocess = true

[ui]
default-command = ["s"]
editor = "vim"
diff-editor = ":builtin"
diff-formatter = ":git"
conflict-marker-style = "git"

[user]
name = "Beth Rennie"
email = "beth@brennie.ca"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  surround("\nJJ: Diff:\n", "", indent("JJ:  ", diff.git(4)))
)
'''

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
