[aliases]
l = ["log", "--reversed"]
s = ["l", "-r", "fork_point(mutable()::@)- | fork_point(mutable()::@)::"]

[git]
subprocess = true

[ui]
default-command = ["s"]
editor = "vim"
diff-editor = ":builtin"
diff-formatter = ":git"
conflict-marker-style = "git"

[user]
name = "Beth Rennie"
email = "beth@brennie.ca"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
