[git]
subprocess = true

[ui]
default-command = "log"
editor = "vim"
paginate = "never"
diff-editor = ":builtin"
conflict-marker-style = "snapshot"

[ui.diff]
format = "git"

[user]
name = "Beth Rennie"
email = "beth@brennie.ca"
