[aliases]
l = ["log", "--reversed"]
s = ["l", "-r", "trunk()::@ | @-::"]

[git]
subprocess = true

[ui]
default-command = ["s"]
editor = "vim"
paginate = "never"
diff-editor = ":builtin"
conflict-marker-style = "snapshot"

[ui.diff]
format = "git"

[user]
name = "Beth Rennie"
email = "beth@brennie.ca"
