[general]
import = ["~/.config/alacritty/tokyo-night-storm.toml"]

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 16

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"
